version: '3'
services:
  user_service:
    image: user_service:latest
    ports:
      - "8081:8081"
    links:
      - post_gres_db
    depends_on:
      - post_gres_db
  post_gres_db:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 020416
      POSTGRES_DB: e-wallet
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5




